export const text = {
  // Homepage
  welcomeTitle: 'Welcome to the Escape Room',
  welcomeSubtitle: 'Do you have what it takes to escape?',
  playButton: 'Play Now',
  
  // Navigation
  login: 'Login',
  signUp: 'Sign Up',
  logout: 'Logout',
  
  // Auth
  email: 'Email',
  password: 'Password',
  retypePassword: 'Retype Password',
  showPassword: 'Show',
  hidePassword: 'Hide',
  createAccount: 'Create Account',
  alreadyHaveAccount: 'Already have an account?',
  dontHaveAccount: "Don't have an account?",
  loginHere: 'Login here',
  createOne: 'Create one',
  userProfileNotFound: 'We could not load your profile. Please try again.',
  userNotIdentified: 'We need your profile to recall progress. Please log in again.',
  
  // Game
  questionNumber: 'Question',
  of: 'of',
  submitAnswer: 'Submit Answer',
  nextQuestion: 'Next Question',
  previousQuestion: 'Previous Question',
  correctAnswer: 'Correct!',
  incorrectAnswer: 'Incorrect. Try again.',
  congratulations: 'Congratulations!',
  youEscaped: 'You have successfully escaped!',
  allLocksUnlocked: 'All locks have been unlocked!',
  
  // Game Initialization
  startNewGame: 'Start New Game',
  recallOldProgress: 'Recall Old Progress',
  selectDifficulty: 'Select Difficulty Level',
  difficultyEasy: 'Easy',
  difficultyMedium: 'Medium',
  difficultyHard: 'Hard',
  timePerQuestion: 'Time per question',
  seconds: 'seconds',
  startingGame: 'Starting game...',
  loadingProgress: 'Loading progress...',
  noProgressFound: 'No saved progress found.',
  
  // Timer
  timeRemaining: 'Time Remaining',
  timeUp: 'Time\'s Up!',
  questionTimeout: 'Time ran out for this question.',
  recallSummaryTitle: 'Latest Run Summary',
  recallSummaryUser: 'Player',
  recallSummaryDifficulty: 'Difficulty',
  recallSummaryFinishedAt: 'Finished at',
  recallSummaryDuration: 'Duration',
  recallSummaryQuestions: 'Questions answered',
  recallSummaryQuestionLabel: 'Question',
  recallSummaryEmpty: 'No question details available for this run.',
  backToMenu: 'Back to Menu',
  unknownQuestion: 'Unknown question',
  unknownDuration: 'Unknown duration',
  unknownFinishedAt: 'Unknown finish time',
  
  // Errors
  invalidCredentials: 'Invalid email or password',
  somethingWentWrong: 'Something went wrong. Try again later.',
  passwordRequirements: 'Password does not meet requirements.',
  passwordsDontMatch: "Passwords don't match!",
  couldNotCreateAccount: 'Could not create account. Try again.',
  
  // Loading
  loading: 'Loading...',
  submitting: 'Submitting...',
  
  // Escape Room Game
  stageCell: 'CELL',
  stageDesk: 'DESK',
  stageEscaped: 'ESCAPED',
  inspectScene: 'Click on the scene to inspect',
  noInspectionText: 'Click on the scene to begin inspection.',
  lockLabel: 'Lock',
  submitLock: 'Submit',
  lockCorrect: 'Correct!',
  lockIncorrect: 'Incorrect. Try again.',
  cellDrawerLock: 'Cell Drawer',
  cellDoorLock: 'Cell Door',
  deskDrawerLock: 'Desk Drawer',
  finalDoorLock: 'Final Door',
  inventory: 'Inventory',
  useItem: 'Use Item',
  itemUsed: 'Item used successfully.',
  cannotUseItem: 'Cannot use item in this context.',
  rod: 'Rod',
  deskKey: 'Key',
  startingNewGame: 'Starting new game...',
  gameSessionError: 'Failed to start game session.',
  inspectionError: 'Failed to inspect scene.',
  lockValidationError: 'Failed to validate lock.',
  itemUsageError: 'Failed to use item.',
  escapedMessage: 'Congratulations! You have successfully escaped the prison!',
  stageTransitionError: 'Cannot transition to this stage yet.',
};
